//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoviesApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MOVIE_WEBModel : DbContext
    {
        public MOVIE_WEBModel()
            : base("name=MOVIE_WEBModel")
        {
        }
    
       /* protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }*/
    
        public virtual DbSet<MOVy> MOVIES { get; set; }
        public virtual DbSet<PERSON_MOVIE> PERSON_MOVIE { get; set; }
        public virtual DbSet<PERSON> PERSONS { get; set; }
        public virtual DbSet<ROLE> ROLES { get; set; }
    }
}
