//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoviesApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSON_MOVIE
    {
        public int ID { get; set; }
        public int Id_Person { get; set; }
        public int Id_Movie { get; set; }
        public int id_Role { get; set; }
    
        public virtual MOVy MOVy { get; set; }
        public virtual PERSON PERSON { get; set; }
        public virtual ROLE ROLE { get; set; }
    }
}
